CREATE DATABASE BaseballDB
GO

USE BaseballDB

CREATE TABLE Team(
TID SMALLINT NOT NULL PRIMARY KEY,
TName NVARCHAR(max) NOT NULL,
City NVARCHAR(max) NOT NULL,
State NVARCHAR(max) NOT NULL, 
League NVARCHAR(max) NOT NULL,
Division NVARCHAR(max) NOT NULL)

GO

CREATE TABLE Player(
PID SMALLINT NOT NULL PRIMARY KEY,
Name NVARCHAR(max) NOT NULL,
Number NVARCHAR NULL,
Position NVARCHAR(max) NULL,
TID SMALLINT NULL)

GO

CREATE TABLE Stat(
PID SMALLINT NOT NUll PRIMARY KEY,
Hits NVARCHAR(max) NULL,
Strikeouts NVARCHAR(max) NULL,
HomeRuns NVARCHAR(max) NULL)

GO
